<!--
  Playground for @spifio/ui.

  This page only runs during development of the library itself. Consuming sites
  don't see it — they import from the `./dist/index.js` entry that's generated by
  svelte-package. Use `pnpm dev` to visit this page and see every component live.
-->
<script lang="ts">
  import { Button, FormField, VehicleCard, type CardVehicle } from '$lib/index.js';

  // Two example vehicles so you can see the featured + sold states side by side.
  const sampleVehicle: CardVehicle = {
    id: 'sample-001',
    year: 2022,
    make: 'Ford',
    model: 'F-150',
    trim: 'XLT SuperCrew 4x4',
    price: 38995,
    mileage: 24150,
    exteriorColor: 'Oxford White',
    bodyStyle: 'Truck',
    condition: 'used',
    featured: true,
    stockNumber: 'F15024',
    imageUrl:
      'https://images.unsplash.com/photo-1612544448445-b8232cff3b6c?w=800&q=80'
  };

  const soldVehicle: CardVehicle = {
    ...sampleVehicle,
    id: 'sample-002',
    year: 2020,
    model: 'Mustang',
    trim: 'GT Premium',
    price: 42500,
    mileage: 18200,
    exteriorColor: 'Race Red',
    bodyStyle: 'Coupe',
    featured: false,
    availability: 'sold',
    imageUrl:
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80'
  };

  let name = $state('');
  let email = $state('');
  let message = $state('');
  let priority = $state('');
</script>

<main class="mx-auto max-w-5xl px-6 py-12 space-y-16">
  <header>
    <p class="text-sm font-semibold text-primary uppercase tracking-wide">@spifio/ui playground</p>
    <h1 class="mt-2 text-4xl font-bold">Shared component library</h1>
    <p class="mt-4 text-muted-foreground max-w-2xl leading-relaxed">
      This is the preview environment for Spif.io's shared SvelteKit 5 components.
      Consuming sites define their own design tokens in their own <code class="text-xs px-1 py-0.5 rounded bg-muted">app.css</code>;
      the same components render in each site's brand palette without conditional code.
    </p>
  </header>

  <section>
    <h2 class="mb-6 text-2xl font-bold">Buttons</h2>
    <div class="flex flex-wrap gap-4 bg-card rounded-xl border border-border p-6">
      <Button variant="primary">Primary CTA</Button>
      <Button variant="outline">Outline</Button>
      <Button variant="white">White</Button>
      <Button disabled>Disabled</Button>
    </div>
    <div class="mt-4 rounded-xl bg-primary p-6">
      <Button variant="dark-outline">On dark background</Button>
    </div>
  </section>

  <section>
    <h2 class="mb-6 text-2xl font-bold">Form fields</h2>
    <form class="grid gap-4 bg-card rounded-xl border border-border p-6 max-w-lg" onsubmit={(e) => e.preventDefault()}>
      <FormField id="name" label="Full name" required bind:value={name} placeholder="Jane Smith" />
      <FormField id="email" type="email" label="Email" required bind:value={email} placeholder="you@example.com" />
      <FormField
        id="priority"
        type="select"
        label="Priority"
        bind:value={priority}
        placeholder="Select priority"
        options={[
          { value: 'low', label: 'Low' },
          { value: 'medium', label: 'Medium' },
          { value: 'high', label: 'High' }
        ]}
      />
      <FormField id="message" type="textarea" label="Message" rows={4} bind:value={message} />
      <Button type="submit">Submit</Button>
    </form>
  </section>

  <section>
    <h2 class="mb-6 text-2xl font-bold">Vehicle cards</h2>
    <div class="grid gap-6 sm:grid-cols-2">
      <VehicleCard vehicle={sampleVehicle} />
      <VehicleCard vehicle={soldVehicle} showBadges showConditionBadge />
    </div>
  </section>
</main>
